### ISSUE TITLE
公域机器人获取频道成员或有权限问题

### ISSUE THREAD

**Issue by TihPct** [Kloping/qqpd-bot-java#11]
版本:`1.4.8`
平台:`Windows`
问题描述:`如果无法获取群员信息,则会返回NULL,如强制使用会报错空指针,此报错会影响机器人无法发送消息`

`建议对获取频道群员操作进行声明或异常捕获`
**代码路径**
`io.github.kloping.qqbot.entities.qqpd.Guild#getMember`

`**原内容**`
```
  public Member getMember(String userId) {
        Member member = BaseUtils.tryGet(Common.GUILD_MEMBER_TEMP, Guild.this.getId(), userId);
        if (member == null) {
            member = bot.guildBase.getMember(Guild.this.getId(), userId);
            MapUtils.append(Common.GUILD_MEMBER_TEMP, Guild.this.getId(), userId, member);
        }
        return member;
    }
```
`**修改内容**`
```
public Member getMember(String userId) {
        try {
            Member member = BaseUtils.tryGet(Common.GUILD_MEMBER_TEMP, Guild.this.getId(), userId);
            if (member == null) {
                member = bot.guildBase.getMember(Guild.this.getId(), userId);
                MapUtils.append(Common.GUILD_MEMBER_TEMP, Guild.this.getId(), userId, member);
            }
            return member;
        } catch (Exception e) {
            return null;
        }
    }
```
`Log`
```
java.lang.NullPointerException
        at io.github.kloping.qqbot.entities.qqpd.Guild.getMember(Guild.java:60)
        at io.github.kloping.qqbot.entities.qqpd.Guild.setMember(Guild.java:68)
        at io.github.kloping.qqbot.impl.BaseMemberUpdateEvent.<init>(BaseMemberUpdateEvent.java:18)
        at io.github.kloping.qqbot.impl.registers.MemberEventRegisters.handle(MemberEventRegisters.java:28)
        at io.github.kloping.qqbot.network.Events.onEvent(Events.java:72)
        at io.github.kloping.qqbot.network.Events.lambda$onReceive$0(Events.java:42)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Kloping** [comment]
什么动作时触发
