### ISSUE TITLE
公域机器人接收到频道消息时,报错空指针

### ISSUE THREAD

**Issue by TihPct** [Kloping/qqpd-bot-java#8]
`备注`
发送包含@机器人的消息时,会触发该空指针异常
`Log`
```

[github.kloping.ST][Error] [05/31-20:28:57:963]=>
 at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:890)
	 at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
	 at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)
	 at io.github.kloping.MySpringTool.h1.impl.component.HttpClientManagerImpl$2.run(HttpClientManagerImpl.java:145)
	 at io.github.kloping.MySpringTool.h1.impl.component.HttpClientManagerImpl$1.invoke(HttpClientManagerImpl.java:105)
	 at com.sun.proxy.$Proxy77.getMembers(Unknown Source)
	 at io.github.kloping.qqbot.api.qqpd.Guild.initTemp0(Guild.java:54)
	 at io.github.kloping.qqbot.api.qqpd.Guild.memberMap(Guild.java:82)
	 at io.github.kloping.qqbot.api.data.message.BaseMessageEvent.<init>(BaseMessageEvent.java:32)
	 at io.github.kloping.qqbot.api.data.message.BaseMessageReceiveEvent.<init>(BaseMessageReceiveEvent.java:15)
	 at io.github.kloping.qqbot.api.data.message.BaseMessageContainsAtEvent.<init>(BaseMessageContainsAtEvent.java:12)
	 at io.github.kloping.qqbot.api.EventManager.factory(EventManager.java:105)
	 at io.github.kloping.qqbot.api.EventManager.lambda$onEvent$0(EventManager.java:83)
	 at java.util.HashMap.forEach(HashMap.java:1290)
	 at io.github.kloping.qqbot.api.EventManager.onEvent(EventManager.java:81)
	 at io.github.kloping.qqbot.WssWorker.lambda$onReceive$0(WssWorker.java:182)
	 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	 at java.util.concurrent.FutureTask.run(FutureTask.java)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:750)
	
java.lang.NullPointerException
	at io.github.kloping.qqbot.api.qqpd.Guild.initTemp0(Guild.java:55)
	at io.github.kloping.qqbot.api.qqpd.Guild.memberMap(Guild.java:82)
	at io.github.kloping.qqbot.api.data.message.BaseMessageEvent.<init>(BaseMessageEvent.java:32)
	at io.github.kloping.qqbot.api.data.message.BaseMessageReceiveEvent.<init>(BaseMessageReceiveEvent.java:15)
	at io.github.kloping.qqbot.api.data.message.BaseMessageContainsAtEvent.<init>(BaseMessageContainsAtEvent.java:12)
	at io.github.kloping.qqbot.api.EventManager.factory(EventManager.java:105)
	at io.github.kloping.qqbot.api.EventManager.lambda$onEvent$0(EventManager.java:83)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at io.github.kloping.qqbot.api.EventManager.onEvent(EventManager.java:81)
	at io.github.kloping.qqbot.WssWorker.lambda$onReceive$0(WssWorker.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by TihPct** [comment]
`这个BUG会影响到sender信息的获取`
```
public BaseMessageEvent(Message message, JSONObject jo) {
        try {
            this.message = message;
            this.metadata = jo;
            this.guild = Resource.starter.getBot().getGuild(message.getGuildId());
            this.channel = (Channel)this.guild.channelMap().get(message.getChannelId());
            this.sender = (Member)this.guild.memberMap().get(message.getAuthor().getId());
        } catch (Exception var4) {
            var4.printStackTrace();
        }

    }
```
`其它问题并未发现`

`代码路径io.github.kloping.qqbot.api.data.message.BaseMessageEvent(Message message, JSONObject jo)`

**我自己手动加上了一个异常捕获,可以保证消息能正常发送,但是sender数据无法被正常赋值**

**Comment by TihPct** [comment]
```
@GetPath("/guilds/{guild_id}/members")
    Member[] getMembers(@PathValue("guild_id") String var1, @ParamName("limit") Integer var2);
```
好像是发送获取频道成员列表的结果为空
